<?php


    namespace blackpanda\virt;


    use Illuminate\Support\ServiceProvider;

    class VirtualizorServiceProvider extends ServiceProvider
    {

        public function register()
        {
            //parent::register(); // TODO: Change the autogenerated stub

            $this->app->bind('virtualizor',function (){
                return new Virtualizor();
            });
        }


        public function boot()
        {
            // Register Publishes

            // Migrations

            $this->publishes([
                __DIR__ . '/../publishes/migrations' => database_path('/migrations'),
            ], 'migrations');

            // Models

            $this->publishes([
                __DIR__ . '/../publishes/models' => app_path('/virt'),
            ], 'models');

            // Factories

            $this->publishes([
                __DIR__ . '/../publishes/factories' => database_path('/factories'),
            ], 'models');

        }

    }
