<?php


    namespace b14ckp4nda\virt;


    use Illuminate\Support\ServiceProvider;

    class VirtualizorServiceProvider extends ServiceProvider
    {

        public function register()
        {
            //parent::register(); // TODO: Change the autogenerated stub

            $this->app->bind('virtualizor',function (){
                return new Virtualizor();
            });
        }


        public function boot()
        {
            // Register Publishes

            // Migrations

            $this->publishes([
                __DIR__ . '/migrations' => database_path('/migrations'),
            ], 'migrations');

        }

    }
